[build-system]
requires = ["hatchling>=1.25.0"]
build-backend = "hatchling.build"

[project]
name = "siscos_nodes"
version = "0.0.1"
authors = [
    { name = "David Sisco" }
]
requires-python = ">=3.12"

[tool.pytest.ini_options]
testpaths = [
  "tests"
]